# generated by datamodel-codegen
# ruff: noqa: D101, D205, E402, E501, F404, RUF100

from __future__ import annotations

from pydantic import BaseModel


class BadRequest(BaseModel):
    message: str


class InternalServerError(BaseModel):
    message: str


class NotFoundError(BaseModel):
    message: str


class LockedError(BaseModel):
    message: str
