# generated by datamodel-codegen
# ruff: noqa: D101, D205, E402, E501, F404, RUF100

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field, RootModel

from .success import SuccessResponse


class SelectorQuery(RootModel[dict[str, str]]):
    """Label selector. Each property name is a label key, and the value
    is the label value for exact match (AND condition).

    """

    root: dict[str, str]


class MatchItem(BaseModel):
    key: Annotated[str, Field(examples=["instance"])]
    """
    The key or name of a label.
    """
    value: Annotated[str, Field(examples=[".*hostA:9100.*"])]
    """
    The value of a label.
    """
    regex: Annotated[bool, Field(examples=[True])] = False
    """
    If true, performs a regular expression match (like PromQL's `=~`). It is exact match otherwise.
    """


class Selector(BaseModel):
    """Selector for filtering time series by multiple label conditions (AND logic)."""

    match: list[MatchItem] | None = None
    """
    Multiple label-key and value pairs can be specified (AND condition).
    """


class ProcessStatus(StrEnum):
    in_progress = "in_progress"
    completed = "completed"
    failed = "failed"


class OperationStatusData(BaseModel):
    process_status: ProcessStatus | None = None
    messages: Annotated[
        str | None,
        Field(
            examples=[
                "Detailed status or error messages, and error manipulation if needed."
            ]
        ),
    ] = None


class OperationStatusResponse(SuccessResponse):
    data: OperationStatusData | None = None


class AddLabelRequest(BaseModel):
    metric_name: Annotated[str, Field(examples=["node_cpu_seconds_total"])]
    """
    The name of a time-series metric.
    """
    new_label_key: Annotated[str, Field(examples=["instance"])]
    """
    The key or name of a label.
    """
    default_value: Annotated[str, Field(examples=["hostA:9100"])]
    """
    The value of a label.
    """
    selector: Selector


class TimeRange(BaseModel):
    start: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    """
    Start of the time range (ISO8601). If not specified, defaults to the earliest available data of the time-series.
    """
    end: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    """
    End of the time range (ISO8601). If not specified, defaults to the latest available data of the time-series.
    """


class ModifyLabelKeyRequest(BaseModel):
    metric_name: Annotated[str, Field(examples=["node_cpu_seconds_total"])]
    """
    The name of a time-series metric.
    """
    range: TimeRange
    selector: Selector
    from_key: str
    """
    The current label key
    """
    to_key: str
    """
    The new label key
    """


class ModifyLabelValueRequest(BaseModel):
    metric_name: Annotated[str, Field(examples=["node_cpu_seconds_total"])]
    """
    The name of a time-series metric.
    """
    range: TimeRange
    """
    The time range for which the label value modification applies.
    """
    selector: Selector
    key: str
    """
    The label key whose value will be changed
    """
    from_value: str
    """
    The current value
    """
    to_value: str
    """
    The new value
    """


class DeleteLabelRequest(BaseModel):
    metric_name: Annotated[str, Field(examples=["node_cpu_seconds_total"])]
    """
    The name of a time-series metric.
    """
    label_keys: list[str]
    selector: Selector
