# generated by datamodel-codegen
# ruff: noqa: D101, D205, E402, E501, F404, RUF100

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field

from .success import SuccessResponse


class PageInfo(BaseModel):
    offset: Annotated[int | None, Field(examples=[0])] = None
    """
    The starting position of the current page.
    """
    limit: Annotated[int | None, Field(examples=[100])] = None
    """
    The maximum number of items per page.
    """
    total: Annotated[int | None, Field(examples=[12345])] = None
    """
    The total number of items available.
    """


class MetricsData(BaseModel):
    metrics: list[str] | None = None
    page: PageInfo | None = None


class MetricsList(SuccessResponse):
    data: MetricsData | None = None


class LabelKeysData(BaseModel):
    metric: Annotated[str | None, Field(examples=["node_cpu_seconds_total"])] = None
    """
    The name of a time-series metric.
    """
    label_keys: list[str] | None = None


class LabelKeysList(SuccessResponse):
    data: LabelKeysData | None = None


class LabelValuesData(BaseModel):
    metric: Annotated[str | None, Field(examples=["node_cpu_seconds_total"])] = None
    """
    The name of a time-series metric.
    """
    label_key: Annotated[str | None, Field(examples=["instance"])] = None
    """
    The key or name of a label.
    """
    values: list[str] | None = None
    page: PageInfo | None = None


class LabelValuesList(SuccessResponse):
    data: LabelValuesData | None = None


class TimeSeriesPayload(BaseModel):
    metric: Annotated[str | None, Field(examples=["node_cpu_seconds_total"])] = None
    """
    The name of a time-series metric.
    """
    labels: dict[str, str] | None = None
    values: list[list[AwareDatetime | str]] | None = None
    """
    An array of [timestamp, value] pairs.
    """
    start: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T11:45:34+09:00"])
    ] = None
    end: Annotated[
        AwareDatetime | None, Field(examples=["2022-10-19T12:45:34+09:00"])
    ] = None
    step: int | None = None
    """
    The downsampling step in seconds.
    """


class TimeSeriesData(SuccessResponse):
    data: TimeSeriesPayload | None = None
