# generated by datamodel-codegen
# ruff: noqa: D101, D205, E402, E501, F404, RUF100

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class SuccessResponse(BaseModel):
    status: Literal["success"] | None = None


class Data(BaseModel):
    operation_id: Annotated[str | None, Field(examples=["20251126T123456_1"])] = None
    """
    A unique identifier for the asynchronous background operation.
    """
    summary: dict[str, Any] | None = None
    """
    A summary of the scheduled operation.
    """


class AcceptedResponse(BaseModel):
    status: Literal["success"] | None = None
    data: Data | None = None
