exporter:
  port: 9102
  timezone: "Asia/Tokyo"

ping:
  timeout: 5
  count: 3
  # targets to monitor
  targets:
    - name: "qube001"
      controller_type: "quel1"
      ip: "qube001"
    - name: "qube002"
      controller_type: "quel1"
      ip: "qube002"
    - name: "qube003"
      controller_type: "quel1"
      ip: "qube003"
