version: 1
disable_existing_loggers: false

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s.%(msecs)03d %(levelname)s %(filename)s:%(lineno)d %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    allowed_fields:
      - asctime
      - msecs
      - levelname
      - filename
      - lineno
      - name
      - message
      - target_host
      - target_ip
      - status
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: /logs/cryo_metrics_exporter.log
    when: "midnight"
    interval: 1
    backupCount: 7
    encoding: utf-8

loggers:
  cryo-metrics-exporter:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
