{
 "title": "Dilution Refrigerator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "canvas",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "refrigerator_temperature{instance=\"$instance\", stage=\"plate_50k\"}",
     "legendFormat": "temperature_50K"
    },
    {
     "expr": "refrigerator_temperature{instance=\"$instance\", stage=\"plate_4k\"}",
     "legendFormat": "temperature_4K"
    },
    {
     "expr": "refrigerator_temperature{instance=\"$instance\", stage=\"still\"}",
     "legendFormat": "temperature_still"
    },
    {
     "expr": "round((refrigerator_temperature{instance=\"$instance\", stage=\"mxc\"} * 1000),0.1)",
     "legendFormat": "temperature_mxc"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\",location=\"chamber_internal\",unit=\"pascal\"}",
     "legendFormat": "pressure_chamber"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\",location=\"exhaust_pump\",unit=\"pascal\"}",
     "legendFormat": "pressure_exhaust_pump"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\",location=\"still_tmp\",unit=\"pascal\"}",
     "legendFormat": "pressure_still_tmp"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\", location=\"tank\",unit=\"kilopascal\"}",
     "legendFormat": "pressure_tank"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\",location=\"before_trap\",unit=\"kilopascal\"}",
     "legendFormat": "pressure_before_trap"
    },
    {
     "expr": "refrigerator_pressure{instance=\"$instance\", location=\"after_trap\",unit=\"kilopascal\"}",
     "legendFormat": "pressure_after_trap"
    },
    {
     "expr": "refrigerator_helium_flow{instance=\"$instance\", unit=\"micromoles per second\"}",
     "legendFormat": "helium_flow"
    }
   ]
  },
  {
   "title": "Temperature (50K plate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "targets": [
    {
     "expr": "refrigerator_temperature{instance=\"$instance\",stage=\"plate_50k\"}",
     "legendFormat": "Temperature (50K plate)"
    }
   ]
  },
  {
   "title": "Temperature (4K plate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "targets": [
    {
     "expr": "refrigerator_temperature{instance=\"$instance\",stage=\"plate_4k\"}",
     "legendFormat": "Temperature (4K plate)"
    }
   ]
  },
  {
   "title": "Temperature (Still plate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "targets": [
    {
     "expr": "refrigerator_temperature{instance=\"$instance\",stage=\"still\"}",
     "legendFormat": "Temperature (Still plate)"
    }
   ]
  },
  {
   "title": "Temperature (MXC plate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mK" } },
   "targets": [
    {
     "expr": "round((refrigerator_temperature{instance=\"$instance\", stage=\"mxc\"} * 1000), 0.1)",
     "legendFormat": "Temperature (MXC plate)"
    }
   ]
  },
  {
   "title": "Pressure / Helium flow / Device status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure (Chamber)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Pa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\",location=\"chamber_internal\",unit=\"pascal\"}",
       "legendFormat": "Pressure (Chamber)"
      }
     ]
    },
    {
     "title": "Pressure (Exhaust pump)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Pa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\", location=\"exhaust_pump\",unit=\"pascal\"}",
       "legendFormat": "Pressure (Exhaust pump)"
      }
     ]
    },
    {
     "title": "Pressure (Still-TMP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Pa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\", location=\"still_tmp\",unit=\"pascal\"}",
       "legendFormat": "Pressure (Still-TMP)"
      }
     ]
    },
    {
     "title": "Pressure (Tank)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "kPa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\", location=\"tank\",unit=\"kilopascal\"}",
       "legendFormat": "Pressure (Tank)"
      }
     ]
    },
    {
     "title": "Pressure (Before TRAP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "kPa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\",location=\"before_trap\",unit=\"kilopascal\"}",
       "legendFormat": "Pressure (Before TRAP)"
      }
     ]
    },
    {
     "title": "Pressure (After TRAP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "kPa" } },
     "targets": [
      {
       "expr": "refrigerator_pressure{instance=\"$instance\",location=\"after_trap\",unit=\"kilopascal\"}",
       "legendFormat": "Pressure (After TRAP)"
      }
     ]
    },
    {
     "title": "Helium flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "μmol/s" } },
     "targets": [
      {
       "expr": "refrigerator_helium_flow{instance=\"$instance\",unit=\"micromoles per second\"}",
       "legendFormat": "Helium flow"
      }
     ]
    },
    {
     "title": "Device status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
     "targets": [
      {
       "expr": "refrigerator_device_status{instance=\"$instance\"}",
       "legendFormat": "{{component}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compressor frequency / Compressor pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compressor frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Hz" } },
     "targets": [
      {
       "expr": "refrigerator_compressor{instance=\"$instance\"}",
       "legendFormat": "{{rotation}}"
      }
     ]
    },
    {
     "title": "Compressor pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MPa" } },
     "targets": [
      {
       "expr": "refrigerator_compressor_pressure{instance=\"$instance\",unit=\"megapascal\"}",
       "legendFormat": "{{side}}"
      }
     ]
    }
   ]
  }
 ]
}