{
 "title": "Qdash-exporter dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_group", "query": ".*" },
   { "name": "chip_id", "query": { "query": "label_values(chip_id)" } },
   { "name": "coupling_group", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "qubit_t1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t1",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t1_average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t1_average",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_echo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_echo",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_echo_average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_echo_average",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_star",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_star",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_anharmonicity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_anharmonicity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_qubit_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_qubit_frequency",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_readout_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_readout_frequency",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_average_readout_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_average_readout_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_average_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_average_gate_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_x90_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_x90_gate_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_x180_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_x180_gate_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_maximum_rabi_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_maximum_rabi_frequency",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_hpi_amplitude",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_hpi_amplitude",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_hpi_length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_hpi_length",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_one_qubit_gate_coherence_limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_one_qubit_gate_coherence_limit",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_zx90_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_zx90_gate_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_zx90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_bell_state_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_bell_state_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_bell_state_fidelity{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_zx90_gate_time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_zx90_gate_time",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_zx90_gate_time{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_two_qubit_gate_coherence_limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_two_qubit_gate_coherence_limit",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_two_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_static_zz_interaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_static_zz_interaction",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_static_zz_interaction{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  }
 ]
}