{
 "title": "Qdash-exporter dashboard for 64 qubits repeat",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_group", "query": ".*" },
   { "name": "chip_id", "query": { "query": "label_values(chip_id)" } },
   {
    "name": "repeat_qubit_t1",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_t1_average",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_t2_echo",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_t2_echo_average",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_t2_star",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_anharmonicity",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_qubit_frequency",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_readout_frequency",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_average_readout_fidelity",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_average_gate_fidelity",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_x90_gate_fidelity",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_x180_gate_fidelity",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_maximum_rabi_frequency",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_hpi_amplitude",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_hpi_length",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   {
    "name": "repeat_qubit_one_qubit_gate_coherence_limit",
    "query": "query_result(sort_by_label_numeric(sum by (group_text,group_value,group_start) ((label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:[0-9]|[1-5][0-9]|6[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"0-63\", \"qubit_id\", \".*\"), \"group_value\", \"(?:[0-9]|[1-5][0-9]|6[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"0\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"64-127\", \"qubit_id\", \".*\"), \"group_value\", \"(?:6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"64\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:12[8-9]|1[3-8][0-9]|19[01])$\"}[30d${__range_s}s]), \"group_text\", \"128-191\", \"qubit_id\", \".*\"), \"group_value\", \"(?:12[8-9]|1[3-8][0-9]|19[01])\", \"qubit_id\", \".*\"), \"group_start\", \"128\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:19[2-9]|2[0-4][0-9]|25[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"192-255\", \"qubit_id\", \".*\"), \"group_value\", \"(?:19[2-9]|2[0-4][0-9]|25[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"192\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))$\"}[30d${__range_s}s]), \"group_text\", \"256-319\", \"qubit_id\", \".*\"), \"group_value\", \"(?:25[6-9]|2[6-9][0-9]|3(?:0[0-9]|1[0-9]))\", \"qubit_id\", \".*\"), \"group_start\", \"256\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:32[0-9]|3[3-7][0-9]|38[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"320-383\", \"qubit_id\", \".*\"), \"group_value\", \"(?:32[0-9]|3[3-7][0-9]|38[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"320\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"384-447\", \"qubit_id\", \".*\"), \"group_value\", \"(?:38[4-9]|39[0-9]|4[0-3][0-9]|44[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"384\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"448-511\", \"qubit_id\", \".*\"), \"group_value\", \"(?:44[8-9]|4[5-9][0-9]|50[0-9]|51[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"448\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:51[2-9]|5[2-6][0-9]|57[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"512-575\", \"qubit_id\", \".*\"), \"group_value\", \"(?:51[2-9]|5[2-6][0-9]|57[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"512\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"576-639\", \"qubit_id\", \".*\"), \"group_value\", \"(?:57[6-9]|5[89][0-9]|6[0-2][0-9]|63[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"576\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:64[0-9]|6[5-9][0-9]|70[0-3])$\"}[30d${__range_s}s]), \"group_text\", \"640-703\", \"qubit_id\", \".*\"), \"group_value\", \"(?:64[0-9]|6[5-9][0-9]|70[0-3])\", \"qubit_id\", \".*\"), \"group_start\", \"640\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:70[4-9]|7[1-5][0-9]|76[0-7])$\"}[30d${__range_s}s]), \"group_text\", \"704-767\", \"qubit_id\", \".*\"), \"group_value\", \"(?:70[4-9]|7[1-5][0-9]|76[0-7])\", \"qubit_id\", \".*\"), \"group_start\", \"704\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])$\"}[30d${__range_s}s]), \"group_text\", \"768-831\", \"qubit_id\", \".*\"), \"group_value\", \"(?:76[8-9]|7[7-9][0-9]|8[0-2][0-9]|83[0-1])\", \"qubit_id\", \".*\"), \"group_start\", \"768\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:83[2-9]|8[4-8][0-9]|89[0-5])$\"}[30d${__range_s}s]), \"group_text\", \"832-895\", \"qubit_id\", \".*\"), \"group_value\", \"(?:83[2-9]|8[4-8][0-9]|89[0-5])\", \"qubit_id\", \".*\"), \"group_start\", \"832\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:89[6-9]|9[0-4][0-9]|95[0-9])$\"}[30d${__range_s}s]), \"group_text\", \"896-959\", \"qubit_id\", \".*\"), \"group_value\", \"(?:89[6-9]|9[0-4][0-9]|95[0-9])\", \"qubit_id\", \".*\"), \"group_start\", \"896\", \"qubit_id\", \".*\") > 0) or (label_replace(label_replace(label_replace(count_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${query_group:pipe}\",qubit_id=~\"^(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))$\"}[30d${__range_s}s]), \"group_text\", \"960-1023\", \"qubit_id\", \".*\"), \"group_value\", \"(?:96[0-9]|9[7-9][0-9]|10(?:0[0-9]|1[0-9]|2[0-3]))\", \"qubit_id\", \".*\"), \"group_start\", \"960\", \"qubit_id\", \".*\") > 0)), \"group_start\"))"
   },
   { "name": "coupling_group", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "qubit_t1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t1 ${repeat_qubit_t1:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 40 },
     "repeat": "repeat_qubit_t1",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t1{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_t1:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t1_average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t1_average ${repeat_qubit_t1_average:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 41 },
     "repeat": "repeat_qubit_t1_average",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t1_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_t1_average:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_echo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_echo ${repeat_qubit_t2_echo:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 42 },
     "repeat": "repeat_qubit_t2_echo",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_echo{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_t2_echo:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_echo_average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_echo_average ${repeat_qubit_t2_echo_average:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 43 },
     "repeat": "repeat_qubit_t2_echo_average",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_echo_average{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_t2_echo_average:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_t2_star",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_t2_star ${repeat_qubit_t2_star:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 44 },
     "repeat": "repeat_qubit_t2_star",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_t2_star{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_t2_star:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_anharmonicity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_anharmonicity ${repeat_qubit_anharmonicity:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 45 },
     "repeat": "repeat_qubit_anharmonicity",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_anharmonicity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_anharmonicity:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_qubit_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_qubit_frequency ${repeat_qubit_qubit_frequency:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 46 },
     "repeat": "repeat_qubit_qubit_frequency",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_qubit_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_qubit_frequency:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_readout_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_readout_frequency ${repeat_qubit_readout_frequency:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 47 },
     "repeat": "repeat_qubit_readout_frequency",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_readout_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_readout_frequency:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_average_readout_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_average_readout_fidelity ${repeat_qubit_average_readout_fidelity:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 48 },
     "repeat": "repeat_qubit_average_readout_fidelity",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_average_readout_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_average_readout_fidelity:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_average_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_average_gate_fidelity ${repeat_qubit_average_gate_fidelity:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 49 },
     "repeat": "repeat_qubit_average_gate_fidelity",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_average_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_average_gate_fidelity:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_x90_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_x90_gate_fidelity ${repeat_qubit_x90_gate_fidelity:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 50 },
     "repeat": "repeat_qubit_x90_gate_fidelity",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_x90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_x90_gate_fidelity:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_x180_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_x180_gate_fidelity ${repeat_qubit_x180_gate_fidelity:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 51 },
     "repeat": "repeat_qubit_x180_gate_fidelity",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_x180_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_x180_gate_fidelity:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_maximum_rabi_frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_maximum_rabi_frequency ${repeat_qubit_maximum_rabi_frequency:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 52 },
     "repeat": "repeat_qubit_maximum_rabi_frequency",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_maximum_rabi_frequency{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_maximum_rabi_frequency:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_hpi_amplitude",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_hpi_amplitude ${repeat_qubit_hpi_amplitude:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 53 },
     "repeat": "repeat_qubit_hpi_amplitude",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_hpi_amplitude{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_hpi_amplitude:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_hpi_length",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_hpi_length ${repeat_qubit_hpi_length:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 54 },
     "repeat": "repeat_qubit_hpi_length",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_hpi_length{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_hpi_length:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "qubit_one_qubit_gate_coherence_limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "qubit_one_qubit_gate_coherence_limit ${repeat_qubit_one_qubit_gate_coherence_limit:text}",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 6, "x": 0, "y": 55 },
     "repeat": "repeat_qubit_one_qubit_gate_coherence_limit",
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_qubit_one_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=\"\",qubit_id=~\"${repeat_qubit_one_qubit_gate_coherence_limit:raw}\",qubit_id=~\"${query_group:pipe}\"}[30d]),\"qubit_id\")",
       "legendFormat": "{{qubit_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_zx90_gate_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_zx90_gate_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_zx90_gate_fidelity{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_bell_state_fidelity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_bell_state_fidelity",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_bell_state_fidelity{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_zx90_gate_time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_zx90_gate_time",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_zx90_gate_time{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_two_qubit_gate_coherence_limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_two_qubit_gate_coherence_limit",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_two_qubit_gate_coherence_limit{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "coupling_static_zz_interaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "coupling_static_zz_interaction",
     "type": "state-timeline",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sort_by_label_numeric(last_over_time(qdash_coupling_static_zz_interaction{chip_id=~\"$chip_id\",coupling_id=~\"${coupling_group:pipe}\",qubit_id=\"\"}[30d]),\"coupling_id\")",
       "legendFormat": "{{coupling_id}}"
      }
     ]
    }
   ]
  }
 ]
}